spring:
  datasource:
    url: jdbc:mysql://localhost:3306/main?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  banner:
    location: banner.txt
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api


